### ISSUE TITLE
Hello, I would like to collaborate with your project by serving as a translator to Spanish which is my native language. I could translate the document readme.md and contributing.md since the translation must be one thousand or more words

### ISSUE THREAD

**Issue by LuigiBaute** [gchiesa/s3vaultlib#43]
* S3Vault Library version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by gchiesa** [comment]
Hi Luigi, 
please feel free to fork the repo, translate the documentation you think is interesting to be localised and add your locale at the end. Like README.es_ES.md and open a pull request. I will review it and add to the main repo.
